=== andreypudov/andreypudov.github.com/data/schemas/album.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://andreypudov.com/data/schemas/album.schema.json",

  "title": "Album",
  "description": "A schema representing a collection of artwork items in an album.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version."
    },
    "name": {
      "type": "string",
      "description": "The title of the album."
    },
    "description": {
      "type": "string",
      "description": "A description of the album."
    },
    "genre": {
      "type": "string",
      "enum": [
        "Nature",
        "Portrait",
        "Street",
        "Other"
      ],
      "description": "The genre of the album."
    },
    "cover": {
      "type": "string",
      "format": "uri-reference",
      "description": "The relative path to the artwork image."
    },
    "items": {
      "type": "array",
      "description": "A list of artwork items included in the album.",
      "items": {
        "$ref": "item.schema.json"
      },
      "minItems": 1
    }
  },
  "required": [
    "$schema",
    "name",
    "description",
    "genre",
    "cover",
    "items"
  ],
  "additionalProperties": false
}

=== andreypudov/andreypudov.github.com/data/photographs/conqueringAsia.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Conquering Asia",
  "description": "",
  "genre": "Street",
  "cover": "/photographs/2025-01-15_02-10/2025-01-15_02-10_001.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_001.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_002.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_003.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_004.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_005.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_006.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_007.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "Lunar Glow on Shennong Street",
      "description": "Lantern-lit Shennong Street glows with festive warmth, celebrating Chinese New Year in timeless, nocturnal elegance.",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_008.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_009.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_010.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_011.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_012.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_013.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_014.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_015.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_016.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_017.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_018.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_019.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_020.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "Whispers of Sunfong Temple",
      "description": "A serene landscape capturing the timeless elegance of Sunfong Temple beneath a gently fading Taiwanese sky.",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_021.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_022.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_023.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_024.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_025.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_026.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_027.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_028.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_029.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_030.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_031.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_032.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_033.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_034.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_035.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_036.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_037.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_038.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "Moonlight Over Taipei 101",
      "description": "Taipei 101 rises into the night sky, crowned by the moon in a quiet moment of urban stillness.",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_039.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_040.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_041.webp",
      "orientation": "portrait",
      "date": "2025-02-10"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-01-15_02-10/2025-01-15_02-10_042.webp",
      "orientation": "landscape",
      "date": "2025-02-10"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/saraMartinGordi.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Sara Martin Gordi",
  "description": "A series of elegant portraits of Sara Martin Gordi posing against the architectural backdrop of Museu Nacional d'Art de Catalunya.",
  "genre": "Portrait",
  "cover": "/photographs/2025-11-15/2025-11-15_005.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_001.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_002.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_003.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_004.webp",
      "orientation": "landscape",
      "date": "2025-11-15"
    },
    {
      "name": "Sara Martin Gordi: Garden Poise",
      "description": "Balancing elegance with Barcelonaâ€™s cultural grandeur.",
      "path": "/photographs/2025-11-15/2025-11-15_005.webp",
      "orientation": "landscape",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_006.webp",
      "orientation": "landscape",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_007.webp",
      "orientation": "landscape",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_008.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/peipeiMadrid.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Pei Pei. Weekend in Madrid",
  "description": "",
  "genre": "Portrait",
  "cover": "/photographs/2024-04-10_30/2024-04-10_30_011.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_001.webp",
      "orientation": "landscape",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_002.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_003.webp",
      "orientation": "landscape",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_004.webp",
      "orientation": "landscape",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_005.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_006.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_007.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_008.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_009.webp",
      "orientation": "landscape",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_010.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "Pei Pei",
      "description": "Weekend in Madrid",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_011.webp",
      "orientation": "landscape",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_012.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_013.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_014.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_015.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_016.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_017.webp",
      "orientation": "landscape",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_018.webp",
      "orientation": "landscape",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_019.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_020.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_021.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_022.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_023.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2024-04-10_30/2024-04-10_30_024.webp",
      "orientation": "portrait",
      "date": "2024-04-30"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/barcelonaAirport.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "LEBL Barcelona El Prat International Airport",
  "description": "",
  "genre": "Street",
  "cover": "/photographs/2023-05-17/2023-05-17_011.webp",
  "items": [
    {
      "name": "Josep Tarradellas Barcelona–El Prat Airport is the largest and busiest airport in Catalonia, and the sixth busiest in Europe. In 2019, Barcelona Airport handled a record 52,686,314 passengers, up 5.0% from 2018. It is a hub for Level and Vueling, and a focus city for Air Europa, Iberia, EasyJet and Ryanair.",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_001.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "Ryanair DAC is an Irish ultra low-cost carrier founded in 1984. It is headquartered in Swords, Dublin, Ireland, and has its primary operational bases at Dublin and London Stansted airports. It forms the largest part of the Ryanair Holdings family of airlines and has Ryanair UK, Buzz, Lauda Europe, and Malta Air as sister airlines. It is Ireland's biggest airline and in 2016 became Europe's largest budget airline by scheduled passengers flown, carrying more international passengers than any other airline.",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_002.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "TAP Air Portugal is the flag carrier of Portugal, headquartered at Lisbon Airport which also serves as its hub. The airline was established on 14 March 1945 and began commercial services on 19 September 1946. TAP – Transportes Aéreos Portugueses – has been a member of the Star Alliance since 2005 and operates on average 2,500 flights a week to 90 destinations in 34 countries worldwide. The company has a fleet of 100 aircraft, all of which are manufactured by Airbus with the exception of 22 aircraft manufactured by Embraer and ATR, operating on behalf of the regional airline TAP Express.",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_003.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "Vueling is a Spanish low-cost airline based at Viladecans in Greater Barcelona with hubs at Barcelona–El Prat Airport (main), Paris-Orly Airport in Paris, France and Leonardo da Vinci–Fiumicino Airport in Rome, Italy (secondary). It is the largest airline in Spain, measured by fleet size and number of destinations. As of 2021, Vueling serves 122 destinations in Africa, Asia, Europe and the Middle East, and carried more than 34 million passengers in 2019. Since 2013, it has been an operating company of International Airlines Group, the parent company of British Airways and Iberia.",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_004.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_005.webp",
      "orientation": "landscape",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_006.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_007.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "LEBL Barcelona El Prat International Airport",
      "description": "An aircraft approaches the threshold of the runway, moments before touchdown at Barcelona’s main airport.",
      "path": "/photographs/2023-05-17/2023-05-17_008.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_009.webp",
      "orientation": "landscape",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "Scandinavian Airlines, more commonly known and styled as SAS, is the flag carrier of Denmark, Norway, and Sweden. Part of the SAS Group and headquartered at the SAS Frösundavik Office Building in Solna, Sweden, the airline operates 180 aircraft to 90 destinations. The airline's main hub is at Copenhagen-Kastrup Airport, with connections to 109 destinations around the world. Stockholm Arlanda Airport is the second largest hub, with Oslo Airport, Gardermoen being the third major hub of SAS. Minor hubs also exist at Bergen Airport, Flesland, Göteborg Landvetter Airport, Stavanger Airport, Sola, and Trondheim Airport, Værnes. SAS Cargo is an independent, wholly owned subsidiary of Scandinavian Airlines and its main office is at Copenhagen Airport.",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_010.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_011.webp",
      "orientation": "landscape",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "Barcelona's first airfield, located at El Remolar, began operations in 1916. However, it did not have good expansion prospects, so a new airport at El Prat opened in 1918. The first plane was a Latécoère Salmson 300 which arrived from Toulouse with final destination Casablanca. The airport was used as headquarters of the Aeroclub of Catalonia and the base for the Spanish Navy's Zeppelin fleet. Scheduled commercial service began in 1927 with an Iberia service to Madrid Cuatro Vientos Airport. This was Iberia's first route. During the time of the Second Spanish Republic El Prat was one of the bases of LAPE (Líneas Aéreas Postales Españolas).",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_012.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_013.webp",
      "orientation": "portrait",
      "date": "2023-05-17",
      "hidden": false
    },
    {
      "name": "The new control tower is a hyperboloid structure",
      "description": "",
      "path": "/photographs/2023-05-17/2023-05-17_014.webp",
      "orientation": "landscape",
      "date": "2023-05-17",
      "hidden": false
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/timelapses/bolshayaPokrovskaya.json
{
  "$schema": "../schemas/album.schema.json",

  "name": "Bolshaya Pokrovskaya",
  "description": "Bolshaya Pokrovskaya Street is the high street in the historical center of Nizhny Novgorod and one of its oldest streets. Until 1917 it was considered a street for noblemen. Formed the main street of the city by the end of the 18th century. It is considered an analog of the Arbat in Moscow or 6-7 Lines of Vasilyevsky Island in St. Petersburg.",
  "genre": "Street",
  "cover": "",
  "items": [
    {
      "name": "",
      "path": "https://player.vimeo.com/video/517762737",
      "orientation": "landscape",
      "date": "2017-04-14"
    }
  ]
}
