=== andreypudov/andreypudov.github.com/data/schemas/album.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://andreypudov.com/data/schemas/album.schema.json",

  "title": "Album",
  "description": "A schema representing a collection of artwork items in an album.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version."
    },
    "name": {
      "type": "string",
      "description": "The title of the album."
    },
    "description": {
      "type": "string",
      "description": "A description of the album."
    },
    "genre": {
      "type": "string",
      "enum": [
        "Nature",
        "Portrait",
        "Street",
        "Other"
      ],
      "description": "The genre of the album."
    },
    "cover": {
      "type": "string",
      "format": "uri-reference",
      "description": "The relative path to the artwork image."
    },
    "items": {
      "type": "array",
      "description": "A list of artwork items included in the album.",
      "items": {
        "$ref": "item.schema.json"
      },
      "minItems": 1
    }
  },
  "required": [
    "$schema",
    "name",
    "description",
    "genre",
    "cover",
    "items"
  ],
  "additionalProperties": false
}

=== andreypudov/andreypudov.github.com/data/photographs/andorra.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Andorra",
  "description": "",
  "genre": "Nature",
  "cover": "/photographs/2022-10-15_16/2022-10-15_16_006.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_001.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "Parc Natural Comunal de les Valls del Comapedrosa\n\nProtected national park in the western portion of Andorra. It contains the highest point in Andorra, Coma Pedrosa, among other peaks.",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_002.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_003.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_004.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_005.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_006.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_007.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_008.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_009.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_010.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_011.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_012.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_013.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_014.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "Mirador Roc Del Quer",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_015.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_016.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_017.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_018.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_019.webp",
      "orientation": "portrait",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "Lake Engolasters",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_020.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_021.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-10-15_16/2022-10-15_16_022.webp",
      "orientation": "landscape",
      "date": "2022-10-16",
      "hidden": false
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/conqueringAmerica3.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Conquering America 3.0",
  "description": "",
  "genre": "Street",
  "cover": "/photographs/2019-05-12_05-25/2019-05-12_05-25_001.webp",
  "items": [
    {
      "name": "Boston is one of the oldest municipalities in America, founded on the Shawmut Peninsula in 1630 by Puritan settlers from the English town of the same name. It was the scene of several key events of the American Revolution and the nation's founding, such as the Boston Massacre, the Boston Tea Party, the Battle of Bunker Hill, and the siege of Boston. Upon American independence from Great Britain, the city continued to be an important port and manufacturing hub as well as a center for education and culture.",
      "description": "",
      "path": "/photographs/2019-05-12_05-25/2019-05-12_05-25_001.webp",
      "orientation": "landscape",
      "date": "2019-05-25",
      "hidden": false
    },
    {
      "name": "The city has expanded beyond the original peninsula through land reclamation and municipal annexation. Its rich history attracts many tourists, with Faneuil Hall alone drawing more than 20Â million visitors per year. Boston's many firsts include the United States' first public park, the first public or state school, the first subway system, and the first large public library. ",
      "description": "",
      "path": "/photographs/2019-05-12_05-25/2019-05-12_05-25_002.webp",
      "orientation": "portrait",
      "date": "2019-05-25",
      "hidden": false
    },
    {
      "name": "Today, Boston is a center of scientific research; the area's many colleges and universities, notably Harvard and MIT, make it a world leader in higher education, including law, medicine, engineering, and business, and the city is considered to be a global pioneer in innovation and entrepreneurship, with nearly 5,000 startups.",
      "description": "",
      "path": "/photographs/2019-05-12_05-25/2019-05-12_05-25_003.webp",
      "orientation": "landscape",
      "date": "2019-05-25",
      "hidden": false
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/peipeiChristmas.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Pei Pei. Christmas lights in Barcelona",
  "description": "Refined portraits set on the sweeping views surrounding Museu Nacional d'Art de Catalunya.",
  "genre": "Portrait",
  "cover": "/photographs/2025-11-27/2025-11-27_001.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-27/2025-11-27_001.webp",
      "orientation": "portrait",
      "date": "2025-11-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-27/2025-11-27_002.webp",
      "orientation": "landscape",
      "date": "2025-11-27"
    },
    {
      "name": "Pei Pei Chen: Luminous Passage",
      "description": "Glows beneath Passeig de Gràcia’s festive lights, merging holiday warmth with urban elegance.",
      "path": "/photographs/2025-11-27/2025-11-27_003.webp",
      "orientation": "landscape",
      "date": "2025-11-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-27/2025-11-27_004.webp",
      "orientation": "portrait",
      "date": "2025-11-27"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/lookingForTheWind.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Looking for the Wind",
  "description": "",
  "genre": "Portrait",
  "cover": "/photographs/2018-05-27/2018-05-27_005.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-05-27/2018-05-27_003.webp",
      "orientation": "landscape",
      "date": "2018-05-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-05-27/2018-05-27_002.webp",
      "orientation": "landscape",
      "date": "2018-05-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-05-27/2018-05-27_006.webp",
      "orientation": "landscape",
      "date": "2018-05-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-05-27/2018-05-27_005.webp",
      "orientation": "landscape",
      "date": "2018-05-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-05-27/2018-05-27_001.webp",
      "orientation": "landscape",
      "date": "2018-05-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-05-27/2018-05-27_004.webp",
      "orientation": "landscape",
      "date": "2018-05-27"
    },
    {
      "name": "Andrey Sudakov",
      "description": "On the eve of a forecasted hurricane â€” a quiet moment before nature's force unfolds.",
      "path": "/photographs/2018-05-27/2018-05-27_007.webp",
      "orientation": "landscape",
      "date": "2018-05-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-05-27/2018-05-27_008.webp",
      "orientation": "portrait",
      "date": "2018-05-27"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/turoDeLHome.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Tur√≥ de l'Home",
  "description": "",
  "genre": "Nature",
  "cover": "/photographs/2022-08-07/2022-08-07_019.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_001.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_002.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_003.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_004.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_005.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_006.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_007.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_008.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_009.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_010.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_011.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_012.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_013.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_014.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_015.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_016.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_017.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_018.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "The summit of Montseny offers sweeping views across Catalonia.",
      "path": "/photographs/2022-08-07/2022-08-07_019.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_020.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_021.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_022.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_023.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_024.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_025.webp",
      "orientation": "portrait",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_026.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_027.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_028.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_029.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_030.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-07/2022-08-07_031.webp",
      "orientation": "landscape",
      "date": "2022-08-07",
      "hidden": false
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/tatyanaBysheva.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Tatyana Bysheva",
  "description": "",
  "genre": "Portrait",
  "cover": "/photographs/2017-07-22/2017-07-22_001.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-07-27/2018-07-27_001.webp",
      "orientation": "portrait",
      "date": "2018-07-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-07-27/2018-07-27_002.webp",
      "orientation": "portrait",
      "date": "2018-07-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-07-27/2018-07-27_003.webp",
      "orientation": "portrait",
      "date": "2018-07-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-07-27/2018-07-27_004.webp",
      "orientation": "portrait",
      "date": "2018-07-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-07-27/2018-07-27_005.webp",
      "orientation": "portrait",
      "date": "2018-07-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2018-07-27/2018-07-27_006.webp",
      "orientation": "portrait",
      "date": "2018-07-27"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2017-07-22/2017-07-22_001.webp",
      "orientation": "landscape",
      "date": "2017-07-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2017-07-22/2017-07-22_004.webp",
      "orientation": "landscape",
      "date": "2017-07-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2017-07-22/2017-07-22_005.webp",
      "orientation": "portrait",
      "date": "2017-07-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2017-07-22/2017-07-22_006.webp",
      "orientation": "portrait",
      "date": "2017-07-22"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/stockholm.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Stockholm. Conquering Scandinavia",
  "description": "",
  "genre": "Street",
  "cover": "/photographs/2022-08-27_09-10/2022-08-27_09-10_032.webp",
  "items": [
    {
      "name": "Rådhuset Station",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_001.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_002.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_003.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_004.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "T-Centralen",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_005.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Stadion Centrum",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_006.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_007.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_008.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Colorful Buildings in Old Town",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_009.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Museum of Medieval",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_010.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Brunkeberg Tunnel",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_011.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_012.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Vasa Museum ",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_013.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_014.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_015.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_016.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_017.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Gröna Lund",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_018.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Nordiska Museet",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_019.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_020.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_021.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_022.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Kastellet",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_023.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_024.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Skyview",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_025.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_026.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Hammarbybacken Topplatå",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_027.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_028.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_029.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_030.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_031.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Old Town",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_032.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_033.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_034.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_035.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "City Hall",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_036.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_037.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_038.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_039.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "Uppsala",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_040.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_041.webp",
      "orientation": "portrait",
      "date": "2022-09-10",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-08-27_09-10/2022-08-27_09-10_042.webp",
      "orientation": "landscape",
      "date": "2022-09-10",
      "hidden": false
    }
  ]
}
