=== andreypudov/andreypudov.github.com/data/schemas/album.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://andreypudov.com/data/schemas/album.schema.json",

  "title": "Album",
  "description": "A schema representing a collection of artwork items in an album.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version."
    },
    "name": {
      "type": "string",
      "description": "The title of the album."
    },
    "description": {
      "type": "string",
      "description": "A description of the album."
    },
    "genre": {
      "type": "string",
      "enum": [
        "Nature",
        "Portrait",
        "Street",
        "Other"
      ],
      "description": "The genre of the album."
    },
    "cover": {
      "type": "string",
      "format": "uri-reference",
      "description": "The relative path to the artwork image."
    },
    "items": {
      "type": "array",
      "description": "A list of artwork items included in the album.",
      "items": {
        "$ref": "item.schema.json"
      },
      "minItems": 1
    }
  },
  "required": [
    "$schema",
    "name",
    "description",
    "genre",
    "cover",
    "items"
  ],
  "additionalProperties": false
}

=== andreypudov/andreypudov.github.com/data/photographs/castilloDeMataplana.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Castillo de Mataplana",
  "description": "",
  "genre": "Nature",
  "cover": "/photographs/2022-07-23_24/2022-07-23_24_008.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_001.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_002.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_003.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_004.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_005.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_006.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_007.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_008.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_009.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_010.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_011.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_012.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_013.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_014.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_015.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_016.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_017.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_018.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_019.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_020.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_021.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_022.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_023.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_024.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_025.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_026.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_027.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_028.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_029.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_030.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_031.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_032.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_033.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_034.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_035.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_036.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_037.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_038.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_039.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_040.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_041.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_042.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_043.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_044.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_045.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_046.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_047.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_048.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_049.webp",
      "orientation": "portrait",
      "date": "2022-07-24"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2022-07-23_24/2022-07-23_24_050.webp",
      "orientation": "landscape",
      "date": "2022-07-24"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/asiaFarakshina.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Asia Farakshina",
  "description": "",
  "genre": "Portrait",
  "cover": "/photographs/2015-08-14/2015-08-14_001.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_001.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_002.webp",
      "orientation": "portrait",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_003.webp",
      "orientation": "portrait",
      "date": "2015-08-14",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_004.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_005.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_006.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": false
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_007.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_008.webp",
      "orientation": "portrait",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_009.webp",
      "orientation": "portrait",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_010.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_011.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_012.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_013.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": true
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2015-08-14/2015-08-14_014.webp",
      "orientation": "landscape",
      "date": "2015-08-14",
      "hidden": true
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/sílviaFernandezPuigdevall.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Sílvia Fernandez Puigdevall",
  "description": "Refined portraits set on the sweeping views surrounding Museu Nacional d'Art de Catalunya.",
  "genre": "Portrait",
  "cover": "/photographs/2025-11-15/2025-11-15_015.webp",
  "items": [
    {
      "name": "Sílvia Fernandez Puigdevall: Rooftop Reverie",
      "description": "Blending Barcelona's skyline with modern grace.",
      "path": "/photographs/2025-11-15/2025-11-15_009.webp",
      "orientation": "landscape",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_010.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_011.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_012.webp",
      "orientation": "landscape",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_013.webp",
      "orientation": "landscape",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_014.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_015.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_016.webp",
      "orientation": "landscape",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_017.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_018.webp",
      "orientation": "landscape",
      "date": "2025-11-15"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-11-15/2025-11-15_019.webp",
      "orientation": "portrait",
      "date": "2025-11-15"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/orianaCoelho.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Oriana Coelho",
  "description": "A timeless studio series featuring Oriana in a simple and classic look. Clean lines, soft lighting, and natural poses highlight her effortless elegance and poise.",
  "genre": "Portrait",
  "cover": "/photographs/2025-05-22/2025-05-22_005.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_001.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_002.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_003.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_004.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "Oriana Coelho",
      "description": "Clean lines, soft lighting, and natural poses highlight effortless elegance and poise.",
      "path": "/photographs/2025-05-22/2025-05-22_005.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_006.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_007.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_008.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_009.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_010.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/annaZhykol.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Anna Zhykol",
  "description": "A refined studio portrait series featuring Anna in a simple and classic style.",
  "genre": "Portrait",
  "cover": "/photographs/2025-05-22/2025-05-22_026.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_016.webp",
      "orientation": "landscape",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_017.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_018.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_019.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_020.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_021.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_022.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_023.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_024.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_025.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "Anna Zhykol",
      "description": "A refined studio portrait in a classic style.",
      "path": "/photographs/2025-05-22/2025-05-22_026.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_027.webp",
      "orientation": "landscape",
      "date": "2025-05-22"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-22/2025-05-22_028.webp",
      "orientation": "portrait",
      "date": "2025-05-22"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/photographs/peipeiKimono.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Pei Pei. Kimono Weekend in Barcelona",
  "description": "",
  "genre": "Portrait",
  "cover": "/photographs/2025-05-11/2025-05-11_001.webp",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-11/2025-05-11_001.webp",
      "orientation": "portrait",
      "date": "2025-05-11"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-11/2025-05-11_002.webp",
      "orientation": "portrait",
      "date": "2025-05-11"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-11/2025-05-11_003.webp",
      "orientation": "portrait",
      "date": "2025-05-11"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-11/2025-05-11_004.webp",
      "orientation": "portrait",
      "date": "2025-05-11"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-11/2025-05-11_005.webp",
      "orientation": "portrait",
      "date": "2025-05-11"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-11/2025-05-11_006.webp",
      "orientation": "portrait",
      "date": "2025-05-11"
    },
    {
      "name": "",
      "description": "",
      "path": "/photographs/2025-05-11/2025-05-11_007.webp",
      "orientation": "portrait",
      "date": "2025-05-11"
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/timelapses/maximGorky.json
{
  "$schema": "../schemas/album.schema.json",
  "name": "Monument to Maxim Gorky",
  "description": "Alexei Maximovich Peshkov popularly known as Maxim Gorky was a Russian writer and political activist. He was nominated five times for the Nobel Prize in Literature. Before his success as an author, he traveled widely across the Russian Empire changing jobs frequently, experiences which would later influence his writing. Gorky was active in the emerging Marxist communist movement. He publicly opposed the Tsarist regime, and for a time closely associated himself with Lenin and Bogdanov's Bolshevik wing of the party.",
  "genre": "Street",
  "cover": "https://player.vimeo.com/video/517762848",
  "items": [
    {
      "name": "Monument to Maxim Gorky",
      "description": "Alexei Maximovich Peshkov popularly known as Maxim Gorky was a Russian writer and political activist. He was nominated five times for the Nobel Prize in Literature. Before his success as an author, he traveled widely across the Russian Empire changing jobs frequently, experiences which would later influence his writing. Gorky was active in the emerging Marxist communist movement. He publicly opposed the Tsarist regime, and for a time closely associated himself with Lenin and Bogdanov's Bolshevik wing of the party.",
      "path": "https://player.vimeo.com/video/517762848",
      "orientation": "landscape",
      "date": "2017-04-14",
      "hidden": false
    }
  ]
}

=== andreypudov/andreypudov.github.com/data/timelapses/stateBank .json
{
  "$schema": "../schemas/album.schema.json",

  "name": "The State Bank of Russia",
  "description": "The Nizhny Novgorod branch of the State Bank on Bolshaya Pokrovskaya Street is one of the most beautiful buildings in Nizhny Novgorod and the entire Volga region. It was built in 1913 to commemorate the 300th anniversary of the Romanovs' House. The ceiling in the building, for which the neo-Russian style was chosen, was painted by the famous artist Ivan Bilibin.",
  "genre": "Street",
  "cover": "",
  "items": [
    {
      "name": "",
      "description": "",
      "path": "https://player.vimeo.com/video/517762910",
      "orientation": "landscape",
      "date": "2017-04-14",
      "hidden": false
    }
  ]
}
